### ISSUE TITLE
 Write Unit Tests for Pdf report feature

### ISSUE THREAD

**Issue by harshvora7** [CSC510SEFALL2024/MyDollarBot-BOTGo#9]
Description: Create unit tests to ensure all components of the new feature work as expected.
Acceptance Criteria: All tests pass successfully.
#7

**Comment by AnuragGorkar** [comment]
Checked all the test cases are passing.
Refer commits: [Changes to test_pdf and pdf](https://github.com/CSC510SEFALL2024/MyDollarBot-BOTGo/pull/24/commits/3789fa903bd63245f70ea612064c718a3b4c4e87)
and [Changes to test_pdf](https://github.com/CSC510SEFALL2024/MyDollarBot-BOTGo/pull/24/commits/8443ca8a8fe47facee5efce7c34119b52fa2004f)
